[package]
name = "ex_tournaments_blossom"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_tournaments_blossom"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
blossom = "0.4.0"