[package]
name = "ex_tournaments_mwm"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_tournaments_mwm"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
mwmatching = "0.1.1"
