on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['25.2.2']
        elixir: ['1.14.3']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: "Get deps"
        run: mix deps.get
      - name: "Check code quality"
        run: mix credo
      - name: "Typecheck"
        run: mix dialyzer
      - name: "Run tests"
        run: mix test --cover
      - name: "Check docs"
        run: mix doctor